### PR TITLE
Interactive Product Demo one

### PR DESCRIPTION
**Pull request by vallejoj**
Started making the swipe feature for the landing page. Right now its
just a few of the same GIFS. Buttons and swipe work right now. The next
step is to start getting a library of sorts connected to the demo so it
produces new GIFs.

### CODE REVIEW

**Comment by bshyong** [comment]
hey @vallejoj this is awesome—great work here!  If you can integrate your interactive demo with the static array of gifs into our current landing page (index.html) I can get it deployed.  Would love to have it up, but unless it's integrated we can't deploy into production.

Here's what the current page looks like now: http://choosefun.com/

We would substitute the component you made into the phone that currently exists.  Thanks for all the work you've done so far!

**Comment by vallejoj** [comment]
Hey Ben,
Sorry its been a busy few hours and the bounty did not make it clear that I
was supposed to toss in the code to the landing page, so I was caught a
little off guard. But I will get it done ASAP.

**Comment by bshyong** [comment]
Yup no worries and no rush! 

—

**Comment by adrianonco** [comment]
@vallejoj , esto tiene muy buena pinta amigo!! ;)

**Pull request closed without merging**
