### PR TITLE
gh-pages

### PR DESCRIPTION
**Pull request by matthelbig**
Updated favicon and open graph info.

### CODE REVIEW

**Comment by bshyong** [comment]
thanks @matthelbig; is there a bounty on Assembly that this is associated with?

**Comment by matthelbig** [comment]
no problem. @bshyong i wasn't sure if i should create one. currently no.
just trying some stuff out with github and adding favicons didn't seem like they would break anything :smile:

**Comment by bshyong** [comment]
Haha thanks for jumping in! If you know Rails or iOS you can help out with the app. With bounties you could earn coins/ownership in the app. I'll create a small one for you to claim. 

—

**Comment by bshyong** [comment]
What's your Assembly username?

## 

Ben Shyong
Co-Founder, Meddik
meddik.com | 909-274-9664

**Comment by matthelbig** [comment]
I am at @mtthlbg

**Comment by adrianonco** [comment]
Hey @matthelbig , say hello to us here man: https://assembly.com/giraff/bounties/176 ;P

And thanks for this!

**Pull request merged**
