### PR TITLE
Bounty 79: Implement landing page

### PR DESCRIPTION
**Pull request by kenrick**
https://assembly.com/giraff/bounties/79

### CODE REVIEW

**Comment by seuros** [comment]
Thanks you.
Use SCSS and image_url, this won't work in production

**Comment by seuros** [comment]
also provide a screen-shoot .

**Comment by bshyong** [comment]
@seuros I think we can host this as a static page on Github; no need to back it with an app. It's a temporary landing page and Mailchimp form so that we can launch while our app is still in the approval process.

**Comment by seuros** [comment]
@bshyong  make sense. :shipit:

**Comment by kenrick** [comment]
fun-landing-page

**Comment by seuros** [comment]
Should we remove the email field ?

**Comment by bshyong** [comment]
We need the email field so people can sign up—we'll swap it for download links to our app once the app is approved.

**Comment by seuros** [comment]
Then it should be an app. :smiley_cat:

**Comment by kenrick** [comment]
@seuros It will post the emails to mailchimp and subscribe them to a mailing list.

**Comment by seuros** [comment]
LGTM :green_heart:

**Comment by kenrick** [comment]
Pushing up boostrap first

**Comment by seuros** [comment]
CDN it http://www.bootstrapcdn.com/

**Comment by bshyong** [comment]
+1 on CDN; easy to include that one line

**Comment by kenrick** [comment]
Same here :+1:  Pushing now

**Comment by kenrick** [comment]
:shipit:

**Pull request merged**
